# Generated by Django 4.2.30 on 2026-04-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_allow_null_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicsite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='importrun',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sourcefeed',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sourcefeed',
            name='source_type',
            field=models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('xlsx', 'XLSX'), ('geojson', 'GeoJSON'), ('api', 'API'), ('html', 'HTML'), ('manual', 'Manual')], max_length=32),
        ),
    ]
